import Head from "next/head";
import Minesweeper from "@/components/Minesweeper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Minesweeper - Sanjog Rijal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Minesweeper />
    </>
  );
}
